### PR TITLE
Fix #277 - Stack overflow in Bin Mon message handler

### LINKED ISSUE #277: Stack overflow if AdmPresetDefinitionsHelper first inited on NNG thread
The NNG threads have limited stack, and if AdmPresetDefinitionsHelper::getSingleton() is first called via an NNG message, it will overflow. This is because construction of the singleton runs a bunch of libadm stuff to parse the common definitions. The crash was observed in the binaural monitoring plugin.

Call stack:
```
 	EAR Binaural Monitoring.vst3!__chkstk() Line 109	
 	EAR Binaural Monitoring.vst3!adm::xml::XmlParser::parse() Line 43
 	EAR Binaural Monitoring.vst3!adm::getCommonDefinitions() Line 163	
 	EAR Binaural Monitoring.vst3!adm::parseXml(std::basic_istream<char,std::char_traits<char>> & stream, adm::xml::ParserOptions options) Line 18
 	EAR Binaural Monitoring.vst3!AdmPresetDefinitionsHelper::AdmPresetDefinitionsHelper() Line 54
 	EAR Binaural Monitoring.vst3!AdmPresetDefinitionsHelper::getSingleton() Line 65
 	EAR Binaural Monitoring.vst3!ear::plugin::BinauralMonitoringBackend::onSceneReceived(ear::plugin::proto::SceneStore store) Line 228
 	[External Code]	
	EAR Binaural Monitoring.vst3!ear::plugin::communication::MonitoringMetadataReceiver::handleReceive(std::error_code ec, nng::Message message) Line 65
 	[External Code]	
 	EAR Binaural Monitoring.vst3!nng::detail::AsyncReadAction::operator()() Line 261
 	[External Code]	
 	EAR Binaural Monitoring.vst3!nng::AsyncIO::callback() Line 227
```

The attached project crashes reliably on windows - tested on 2 machines. REAPER v7 (and i think the other machine was v6.something). IIRC, the stack is bigger on MacOS so probably won't crash. [bin mon crash project.zip](https://github.com/ebu/ear-production-suite/files/15211081/bin.mon.crash.project.zip)

I see two solutions.

1. Bump the threads stack size. We've done this elsewhere by calling the message processing it in yet another thread so we're not using NNGs thread.  SceneGainsCalculator for normal LS monitoring plugins - https://github.com/ebu/ear-production-suite/blob/77184d2a17594ca671925e80f1c5e2676c2f5419/ear-production-suite-plugins/lib/src/scene_gains_calculator.cpp#L57-L58
2. Always instantiate AdmPresetDefinitionsHelper on main thread on plugin startup.

Maybe it makes sense for all NNG message callbacks to launch in their own thread? This is bound to trip us up again.

Tagging @rsjbailey for suggestions.

### PR DESCRIPTION
**Pull request by firthm01**
As per #277, a crash would occur (probably only on windows) if the `AdmPresetDefinitionsHandler` was first instantiated as a singleton via an NNG message, due to the NNG threads having a small stack. We had previously overcome a similar issue in the LS monitoring plugins by wrapping `SceneGainsCalculator::update` code in a thread. I used a similar fix here, but it made sense for the thread launching to occur further up the call stack since for both the LS mons and Bin mon, the message handler call stems from `MonitoringMetadataReceiver::handleReceive`

LS mon call stack from message received to `SceneGainsCalculator::update` where a new thread would be launched:
```
	EAR Monitoring 9+10+3.vst3!ear::plugin::SceneGainsCalculator::update(ear::plugin::proto::SceneStore store) Line 56
 	EAR Monitoring 9+10+3.vst3!ear::plugin::MonitoringBackend::updateActiveGains(ear::plugin::proto::SceneStore store) Line 63
 	EAR Monitoring 9+10+3.vst3!ear::plugin::MonitoringBackend::onSceneReceived(ear::plugin::proto::SceneStore store) Line 52
 	[External Code]	
 	EAR Monitoring 9+10+3.vst3!ear::plugin::communication::MonitoringMetadataReceiver::handleReceive::__l9::<lambda_1>::operator()() Line 70
 	[External Code]	
 	EAR Binaural Monitoring.vst3!nng::detail::AsyncReadAction::operator()() Line 261
 	[External Code]	
 	EAR Binaural Monitoring.vst3!nng::AsyncIO::callback() Line 227
```

Bin mon call stack from message received to stack overflow (still on NNG thread)
```
	EAR Binaural Monitoring.vst3!__chkstk() Line 109	
 	EAR Binaural Monitoring.vst3!adm::xml::XmlParser::parse() Line 43
 	EAR Binaural Monitoring.vst3!adm::getCommonDefinitions() Line 163	
 	EAR Binaural Monitoring.vst3!adm::parseXml(std::basic_istream<char,std::char_traits<char>> & stream, adm::xml::ParserOptions options) Line 18
 	EAR Binaural Monitoring.vst3!AdmPresetDefinitionsHelper::AdmPresetDefinitionsHelper() Line 54
 	EAR Binaural Monitoring.vst3!AdmPresetDefinitionsHelper::getSingleton() Line 65
 	EAR Binaural Monitoring.vst3!ear::plugin::BinauralMonitoringBackend::onSceneReceived(ear::plugin::proto::SceneStore store) Line 228
 	[External Code]	
	EAR Binaural Monitoring.vst3!ear::plugin::communication::MonitoringMetadataReceiver::handleReceive(std::error_code ec, nng::Message message) Line 65
 	[External Code]	
 	EAR Binaural Monitoring.vst3!nng::detail::AsyncReadAction::operator()() Line 261
 	[External Code]	
 	EAR Binaural Monitoring.vst3!nng::AsyncIO::callback() Line 227
```

Fix was to launch message handlers in new threads from the common `MonitoringMetadataReceiver::handleReceive` method.

Closes #277

### CODE REVIEW

File: ear-production-suite-plugins/lib/src/communication/monitoring_metadata_receiver.cpp [hunk 1]
```diff
@@ -62,7 +63,12 @@ void MonitoringMetadataReceiver::handleReceive(std::error_code ec,
       if (!sceneStore.ParseFromArray(message.data(), message.size())) {
         throw std::runtime_error("Failed to parse Scene Object");
       }
-      handler_(std::move(sceneStore));
+      // Called by NNG callback on thread with small stack.
+      // Launch task in another thread to overcome stack limitation.
+      auto future = std::async(std::launch::async, [this, sceneStore]() {
+        handler_(sceneStore);
```
Comment (firthm01) [inline ear-production-suite-plugins/lib/src/communication/monitoring_metadata_receiver.cpp:69]: This bit isn't ideal. I think this causes a copy, but probably best to do anyway to ensure lifetime. Using std::move makes the compiler complain because `sceneStore` is apparently a const here... not sure if that happens as part of the capture list?
Could we/should we just widen the lambda to the whole `if (!ec)` block? we must make sure waitForMetadata() is included in that case, so it only occurs after we've read the data (i.e, thread has executed)

Comment (firthm01) [reply ear-production-suite-plugins/lib/src/communication/monitoring_metadata_receiver.cpp:69]: I believe this is fixed by [d216065](https://github.com/ebu/ear-production-suite/pull/278/commits/d2160659b0e8d87542d04b1625e06f0417f5043e)

Comment (rsjbailey) [reply ear-production-suite-plugins/lib/src/communication/monitoring_metadata_receiver.cpp:69]: Would marking the lambda as mutable fix the const warning?

Comment (firthm01) [reply ear-production-suite-plugins/lib/src/communication/monitoring_metadata_receiver.cpp:69]: Just to clarify as the later commit makes my message confusing. This code causes a compiler warning;
```
auto future = std::async(std::launch::async, [this, sceneStore]() {
    handler_(std::move(sceneStore));
});
```
The current code (below) it's happy with, but I'm not sure if this still causes a copy from the capture list to passing in to `handle_` ;
```
auto future = std::async(std::launch::async, [this, sceneStore = std::move(sceneStore)]() {
    handler_(sceneStore);
});
```

Comment (firthm01) [reply ear-production-suite-plugins/lib/src/communication/monitoring_metadata_receiver.cpp:69]: I guess passing a std::shared_ptr<SceneStore> would make it totally clear a copy won't happen.

Comment (firthm01) [reply ear-production-suite-plugins/lib/src/communication/monitoring_metadata_receiver.cpp:69]: Ahh thanks for the explanation - that makes sense why it complains!

Comment (rsjbailey) [reply ear-production-suite-plugins/lib/src/communication/monitoring_metadata_receiver.cpp:69]: I'm not sure why the handler doesn't just take a const reference, maybe it should? (I've not checked to see what it's doing at the other end, if it needs to keep hold of a copy then passing by value makes sense)

Comment (firthm01) [reply ear-production-suite-plugins/lib/src/communication/monitoring_metadata_receiver.cpp:69]: Two handlers... both just read, so I think that makes sense just to pass a const ref.

Bin plugin does it all in https://github.com/ebu/ear-production-suite/blob/main/ear-production-suite-plugins/lib/src/binaural_monitoring_backend.cpp#L203

LS plugins a bit more complicated as it gets passed through a few funcs, but non of them need a non-const:
https://github.com/ebu/ear-production-suite/blob/main/ear-production-suite-plugins/lib/src/monitoring_backend.cpp#L50
https://github.com/ebu/ear-production-suite/blob/main/ear-production-suite-plugins/lib/src/monitoring_backend.cpp#L60
https://github.com/ebu/ear-production-suite/blob/main/ear-production-suite-plugins/lib/src/scene_gains_calculator.cpp#L56

Comment (firthm01) [reply ear-production-suite-plugins/lib/src/communication/monitoring_metadata_receiver.cpp:69]: Changed to const refs in [ab7adb9](https://github.com/ebu/ear-production-suite/pull/278/commits/ab7adb945015cb50ad2e241ac4274c2fff7f3558)

Comment (rsjbailey) [reply ear-production-suite-plugins/lib/src/communication/monitoring_metadata_receiver.cpp:69]: Looks good, could capture by reference in the async lambda too (as we're immediately blocking on it's completion)

```c++
auto future = std::async(std::launch::async, [this, &sceneStore]() {
    handler_(sceneStore);
});
future.get(); //blocking

**Review by rsjbailey — APPROVED** [review]
